name: dashtronaut
description: Slide Puzzle Game Made With Flutter For The Flutter Puzzle Hack Challenge

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+18

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  collection: ^1.16.0
  provider: ^6.0.3
  equatable: ^2.0.3
  package_info_plus: ^1.4.2
  rive: ^0.8.4
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  get_it: ^7.2.0
  share_plus: ^4.0.4
  path_provider: ^2.0.10
  http: ^0.13.4
  url_launcher: ^6.1.2
  font_awesome_flutter: ^10.1.0
  desktop_window: ^0.4.0
  cross_file: ^0.3.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.2.1
  mocktail: ^0.3.0
  path_provider_platform_interface: ^2.0.4
  plugin_platform_interface: ^2.1.2
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/puzzle-solved/
    - assets/rive/
    - assets/images/background/
  fonts:
   - family: PaytoneOne
     fonts:
       - asset: assets/fonts/PaytoneOne/PaytoneOne-Regular.ttf
   - family: Montserrat
     fonts:
       - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
       - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
         weight: 700

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app-icon-with-dash-ltr.png"